package forgeinit

import "strings"

// Render produces the forge.md content string from a Detection.
func Render(d Detection) string {
	var sb strings.Builder

	sb.WriteString("# Forge Project Config\n")
	sb.WriteString("# Generated by `forge init`. Edit as needed.\n\n")

	if d.BuildCmd != "" {
		sb.WriteString("build: ");sb.WriteString(d.BuildCmd);sb.WriteString("\n")
	}
	if d.TestCmd != "" {
		sb.WriteString("test: ");sb.WriteString(d.TestCmd);sb.WriteString("\n")
	}
	if len(d.Languages) > 0 {
		sb.WriteString("language: ");sb.WriteString(strings.Join(d.Languages, ", "));sb.WriteString("\n")
	}

	sb.WriteString("\n## Notes\n")
	sb.WriteString("# Add project-specific conventions here:\n")
	sb.WriteString("# style:\n")
	sb.WriteString("# banned:\n")
	sb.WriteString("# frozen:\n")

	if d.HasGit {
		sb.WriteString("\n## Git\n")
		sb.WriteString("git: true\n")
	}

	if d.HasDocker {
		sb.WriteString("\n## Docker\n")
		sb.WriteString("docker: true\n")
	}

	// MCP servers section — always include a header so users discover the feature.
	sb.WriteString("\n## MCP Servers\n")
	sb.WriteString("# Connect Forge to external tools via MCP (Model Context Protocol).\n")
	sb.WriteString("# Remove the leading '#' from a block below to enable a server.\n")
	sb.WriteString("# Full format docs: see README.md ## MCP configuration\n\n")

	if len(d.SuggestedMCPServers) > 0 {
		for _, s := range d.SuggestedMCPServers {
			// Active (uncommented) blocks for detected servers.
			sb.WriteString("# ")
			sb.WriteString(s.Comment)
			sb.WriteString("\n")
			sb.WriteString(s.Block)
			sb.WriteString("\n\n")
		}
	} else {
		// No servers detected — include commented-out examples for all three
		// common servers so the user can uncomment the right one.
		sb.WriteString(commentBlock(`[[mcp.servers]]
name = "filesystem"
transport = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/path/to/allow"]`))
		sb.WriteString("\n\n")
		sb.WriteString(commentBlock(`[[mcp.servers]]
name = "github"
transport = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
env.GITHUB_PERSONAL_ACCESS_TOKEN = "ghp_your_token_here"`))
		sb.WriteString("\n\n")
		sb.WriteString(commentBlock(`[[mcp.servers]]
name = "playwright"
transport = "stdio"
command = "npx"
args = ["@playwright/mcp@latest"]`))
		sb.WriteString("\n")
	}

	return sb.String()
}

// commentBlock prefixes every non-empty line in a multi-line block with "# ",
// for use in forge.md template output where examples should be commented out.
func commentBlock(block string) string {
	var sb strings.Builder
	for _, line := range strings.Split(block, "\n") {
		if strings.TrimSpace(line) == "" {
			sb.WriteString("\n")
		} else {
			sb.WriteString("# ")
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}
	return strings.TrimRight(sb.String(), "\n")
}
