package forgeinit

import "strings"

// Render produces the forge.md content string from a Detection.
func Render(d Detection) string {
	var sb strings.Builder

	sb.WriteString("# Forge Project Config\n")
	sb.WriteString("# Generated by `forge init`. Edit as needed.\n\n")

	if d.BuildCmd != "" {
		sb.WriteString("build: " + d.BuildCmd + "\n")
	}
	if d.TestCmd != "" {
		sb.WriteString("test: " + d.TestCmd + "\n")
	}
	if len(d.Languages) > 0 {
		sb.WriteString("language: " + strings.Join(d.Languages, ", ") + "\n")
	}

	sb.WriteString("\n## Notes\n")
	sb.WriteString("# Add project-specific conventions here:\n")
	sb.WriteString("# style:\n")
	sb.WriteString("# banned:\n")
	sb.WriteString("# frozen:\n")

	if d.HasGit {
		sb.WriteString("\n## Git\n")
		sb.WriteString("git: true\n")
	}

	if d.HasDocker {
		sb.WriteString("\n## Docker\n")
		sb.WriteString("docker: true\n")
	}

	return sb.String()
}
